### ISSUE TITLE
`cargo build` failed

### ISSUE THREAD

**Issue by microyahoo** [datenlord/rdma-sys#9]
```
🍺 /root/go/src/github.com/datenlord/rdma-sys ☞ git:(master) ✗ cargo build
   Compiling rdma-sys v0.1.0 (/root/go/src/github.com/datenlord/rdma-sys)
error[E0412]: cannot find type `__uint32_t` in this scope
   --> src/verbs.rs:503:15
    |
503 |     let mask: __uint32_t = 0x000000ff;
    |               ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `rdma-sys` due to previous error
```
https://github.com/datenlord/rdma-sys/blob/2bb2c5bd7e58f5f8bc5584cfacc16c6587664e7c/src/verbs.rs#L503

**Comment by microyahoo** [comment]
@pwang7

**Comment by pwang7** [comment]
Hi, thanks for the reporting it @microyahoo.

This is a simple issue, would you please kindly fix it?

**Comment by microyahoo** [comment]
Are these libraries (rdma-sys and [async-rdma](https://github.com/datenlord/async-rdma)) currently used in production environment? Is it still being maintained? I am currently investigating the rmda solutions.

**Comment by pwang7** [comment]
yes, it's under development, rdma-sys is just a Rust wrapper to ibverbs, async-rdma is to leverage Rust async to provide a better RDMA API.

**Comment by microyahoo** [comment]
Thanks for your reply. I noticed that there is very little documentation related to the repo right now. Are there any plans to improve the documentation?
In addition, I have submiited a PR, PTAL.

**Comment by pwang7** [comment]
> Thanks for your reply. I noticed that there is very little documentation related to the repo right now. Are there any plans to improve the documentation? In addition, I have submiited a PR, PTAL.

This RDMA Rust project is still working in progress, once it's stabled, we'll definitely add more documentation.

BTW, I fixed the build failure, also upgrade bindgen #11, let me know if nay further issue.

**Comment by pwang7** [comment]
> Are these libraries (rdma-sys and [async-rdma](https://github.com/datenlord/async-rdma)) currently used in production environment? Is it still being maintained? I am currently investigating the rmda solutions.

BTW, may I ask what kind of scenario would you like to apply RDMA to?

**Comment by microyahoo** [comment]
Currently, tikv only support [grpc](https://github.com/tikv/grpc-rs), I am investigating whether it is feasible to replace grpc with [tonic](https://github.com/hyperium/tonic) and integrate RDMA to support dual stack. Welcome to comment on it, thanks.

**Comment by pwang7** [comment]
> Currently, tikv only support [grpc](https://github.com/tikv/grpc-rs), I am investigating whether it is feasible to replace grpc with [tonic](https://github.com/hyperium/tonic) and integrate RDMA to support dual stack. Welcome to comment on it, thanks.

I think it's doable. TensorFlow already has its network support [gRPC over RDMA](https://github.com/tensorflow/networking), but it's not for general gRPC. Tonic has some adapter to support different underlying network layer.

**Comment by microyahoo** [comment]
Yes, I have noticed the discussion of [tensorflow](https://github.com/tensorflow/tensorflow/issues/2916). 
In addition, tonic already supports other transports than h2/tcp through [Endpoint::connect_with_connector](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.connect_with_connector) and [Server::serve_with_incoming](https://docs.rs/tonic/latest/tonic/transport/server/struct.Router.html#method.serve_with_incoming).
Thanks for your advice.
